# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf01f439bfdc1134118e6d2cae5b9d698074b0e5b48d0e4a7388c55a36eb2a915ee7d9dea6912f9a1b3881b0638c4d5ab8edb7756888bc4906c4b53491a8d959

test:
  secret_key_base: ec177de3f6af3500e1f3ae04c0856a552205ed2b19bc6e72acbbf1a23047027305cc89765aae79070f7fa93e90e3d25a5dd5a877db41082e574a4dd0b38e0c71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
